_admin_security:
    resource: "@BoShurikAdminBundle/Resources/config/routing/security.yml"
    prefix:   /

_admin_dashboard:
    resource: "@BoShurikAdminBundle/Resources/config/routing/dashboard.yml"
    prefix:   /

_admin_routing:
    resource: "@BoShurikAdminBundle/Resources/config/routing/admin/routing.yml"
    prefix:   /