{% if not append %}
services:
{% endif %}
    {{ vendor }}_{{ bundle_name }}.admin.{{ service_name }}:
        class: {{ namespace }}\Controller\Admin{{ entity_namespace ? '\\' ~ entity_namespace : '' }}\{{ entity_class }}Controller
        arguments:
            - '@service_container'
        tags:
            - { name: boshurik.admin }

